version: '3.8'

services:

  db:
    image: postgres:15
    container_name: lms_db
    restart: always
    environment:
      POSTGRES_DB: bitlab_lms
      POSTGRES_USER: bitlab
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitlab"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lms_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  pgdata:
