spring:
  datasource:
    url: jdbc:postgresql://db:5432/bitlab_lms
    username: bitlab
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: info
    org.springframework: info
    kz.bitlab: debug
